### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by mAAdhaTTah** [davidguttman/sassify#18]
Any chance you can bump the version number? I'm having issues manipulating the Sass options, and I'm wondering if the latest version helps or if I'm just doing something wrong. I'm trying to inject node-bourbon/neat into sassify, but having issues.

**Comment by call-a3** [comment]
I'm not entirely sure I understand what you are asking for... The current (production) dependencies should resolve to the latest version of node-sass. (See [david-dm](https://david-dm.org/call-a3/sassify#info=dependencies&view=table).) 

If you have an older install of sassify, try removing and reinstalling it or running `npm update` (since the original requirement is 2.0.0-beta, it is possible that this is the currently installed version on your system. However, the semantic version should resolve to 2.0.1 when you reinstall. If you tried reinstalling, please verify which version of the dependencies are currently installed?)

Could you post the config that you use to include bourbon-neat in your build? That way I might be better able to understand your issue and/or try to reproduce it.

**Comment by mAAdhaTTah** [comment]
Sorry, this was a terribly written issue, and I decided to go a different route anyway, but thanks for your help.
