### ISSUE TITLE
Support for programmatic transform options

### ISSUE THREAD

**Issue by chrishoage** [davidguttman/sassify#19]
I would like to pass in transform options in the bundle.transform() method like on [this line](https://github.com/chrishoage/lastfm-tunes/blob/master/gulpfile.js#L63). 

I [hacked in support](https://github.com/chrishoage/sassify/blob/master/lib/index.js#L13) but am not entirely happy with it. Do you have advice on what would be best practice for supporting both (either though Object.assign or some other means?) 

If so please let me know how you would like to support this, and I will submit a pull request with support. 

Thank you!

**Comment by call-a3** [comment]
Personally I think it's fine to support it like this. However, I would use the extend() function instead of just using an OR-switch. That way, it's possible to combine "static" settings from a config file with "on-the-fly" settings that are added programatically without overriding one or the other completely...
