### ISSUE TITLE
Support for post-processors

### ISSUE THREAD

**Issue by chrishoage** [davidguttman/sassify#20]
What would be the best approach for supporting post processors (autoprefixer)

I [hacked in support](https://github.com/chrishoage/sassify/blob/master/lib/index.js#L33) for it but this is not acceptable to merge in. Please advise what approach is best to support post processors and I will submit a pull request. 

Thank you!

**Comment by call-a3** [comment]
I think in order to cleanly support other transforms/post-processors, we should look into decoupling sassify and cssify for inlining. Any method of supporting other transforms will probably feel quite hacky if we're just replicating browserifys built-in functionality. 

I think we should refactor sassify to be a transform that just turns sass files into css files and re-emits them into the browserify pipeline. It should then be easy to add other transforms to browserify which detect css and do their own transformation (such as autoprefixing) and lastly add the cssify transform which should also detect the css and inline/auto-inject it.

This is just my opinion though, I'd hang on and see what David has to say on this...

**Comment by davidguttman** [comment]
Don't love the idea of splitting sassify and cssify -- I think it would be annoying to have to depend on both.

Other than that, I'm not really sure what the best approach is -- open to ideas.

**Comment by faergeek** [comment]
It's actually good to follow @call-a3 advice, transforms should be composable as much as possible. 
For example, how about pipeline like this

```
preprocessor (sass|less|stylus) =>
css-modules =>
some custom postcss plugins =>
<anything you want (minifiers, beautifiers> =>
cssify to inject styles in browser or write file
```

Just think about how you'd use `uglifyify` or something like that for js, it's natural.

**Comment by chrishoage** [comment]
agreed. closing this.

**Comment by faergeek** [comment]
I still would like to hear what @davidguttman thinks about it.

**Comment by davidguttman** [comment]
@faergeek Not sure I have any additional input. I just don't like the idea of needing to require both `sassify` _and_ `cssify`

**Comment by faergeek** [comment]
So how would you use it in flexible way then?

**Comment by faergeek** [comment]
Please take a look at https://gist.github.com/substack/68f8d502be42d5cd4942#gistcomment-1612205

How would you implement something like that (I'm talking about composability of transforms `stylusify/sassify/lessify` => `postcssify` => `cssify`)?
